//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diachkov_College.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiachkovCollegeEntities : DbContext
    {
        public DiachkovCollegeEntities()
            : base("name=DiachkovCollegeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Activity> Activity { get; set; }
        public DbSet<Direction> Direction { get; set; }
        public DbSet<Group> Group { get; set; }
        public DbSet<Journal> Journal { get; set; }
        public DbSet<Spesial> Spesial { get; set; }
    }
}
